# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{evernote}
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Sepic"]
  s.date = %q{2010-03-19}
  s.email = %q{chris.sepic@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mkd"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.mkd",
     "Rakefile",
     "VERSION",
     "evernote.gemspec",
     "lib/evernote.rb",
     "lib/evernote/client.rb",
     "lib/evernote/note_store.rb",
     "lib/evernote/user_store.rb",
     "spec/evernote/auth.yaml",
     "spec/evernote/client_spec.rb",
     "spec/evernote/note_store_spec.rb",
     "spec/evernote/user_store_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "vendor/gen-rb/evernote.rb",
     "vendor/gen-rb/evernote/edam/errors_types.rb",
     "vendor/gen-rb/evernote/edam/limits_constants.rb",
     "vendor/gen-rb/evernote/edam/limits_types.rb",
     "vendor/gen-rb/evernote/edam/note_store.rb",
     "vendor/gen-rb/evernote/edam/note_store_constants.rb",
     "vendor/gen-rb/evernote/edam/note_store_types.rb",
     "vendor/gen-rb/evernote/edam/types_constants.rb",
     "vendor/gen-rb/evernote/edam/types_types.rb",
     "vendor/gen-rb/evernote/edam/user_store.rb",
     "vendor/gen-rb/evernote/edam/user_store_constants.rb",
     "vendor/gen-rb/evernote/edam/user_store_types.rb"
  ]
  s.homepage = %q{http://github.com/cgs/evernote}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{High level wrapper for the Evernote API}
  s.test_files = [
    "spec/evernote/client_spec.rb",
     "spec/evernote/note_store_spec.rb",
     "spec/evernote/user_store_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thrift_client>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<thrift_client>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<thrift_client>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

